version: 3.8

services:
  potree-frontend-prod:
    container_name: potree-frontend-prod
    volumes:
      - ./deploy/nginx/default.conf:/etc/nginx/conf.d/default.conf
    build:
      context: ..
      dockerfile: Dockerfile
    ports:
      - '49201:80'
